Update install.sh
FIxing forever starting problem

Forever was failing with the error:
```
error: Forever detected script exited with code: 0
```

Solution: use `forever start  /opt/tabinsight-server-v2/app/bin/www` instead of `forever start  /opt/tabinsight-server-v2/app/app.js`